server:
  port: 8071
#  context-path: /teacher

spring:
  application:
    name: tss-teacher

eureka:
  client:
    serviceUrl:
      defaultZone: http://dev.tss.com:8090/eureka/
#  instance:
#    metadata-map:
#      management:
#        context-path: ${server.context-path}/actuator
#    health-check-url: http://dev.tss.com:${server.port}${server.context-path}/actuator/health
#    status-page-url: http://dev.tss.com:${server.port}${server.context-path}/swagger-ui.html
#    status-page-url: http://dev.tss.com:${server.port}${server.context-path}/actuator/info
#    home-page-url: http://dev.tss.com:${server.port}/
    
#feign:
#  hystrix:
#      enabled: false

logging:
  level:
    root: INFO
    com.tss: DEBUG

account:
  contextPath: /account 
  serviceId: account
report:
  serviceId: TSS-REPORT
