server:
  port: 8071
#  context-path: /teacher

logging:
  level:
    root: INFO
    com.tss: DEBUG

user:
  student:
    infoUrl: http://localhost:8080/student/getLoginInfo
  teacher:
    infoUrl: http://localhost:8080/teacher/getLoginInfo

spring:
  application:
    name: tss-teacher
  zipkin:
    base-url: http://localhost:8093
    sleuth:
      sampler:
        # 100%的概率将链路的数据上传给Zipkin Server，默认0.1
        percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
#  instance:
#    metadata-map:
#      management:
#        context-path: ${server.context-path}/actuator
#    health-check-url: http://dev.tss.com:${server.port}${server.context-path}/actuator/health
#    status-page-url: http://dev.tss.com:${server.port}${server.context-path}/swagger-ui.html
#    status-page-url: http://dev.tss.com:${server.port}${server.context-path}/actuator/info
#    home-page-url: http://dev.tss.com:${server.port}/
    
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 10000



account:
  serviceId: TSS-ACCOUNT
report:
  serviceId: TSS-REPORT
